### ISSUE TITLE
H2 Küldés#1

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#2]
A H2 részhatáridőre teljesítendő feladatok

A követelmény analízis fázis dokumentumainak feltöltése.

Erre a határidőre el kell készíteni, és a külön kiadott feltöltési útmutató szerint fel kell tölteni az alábbi anyagokat:

1. A Vízió dokumentum

Egy ajánlott felépítés megtalálható a dokumentum minták között. A minta dokumentum elé természetesen be kell illeszteni a „címlapot”. A dokumentum stílusai, a betűtípusok és a betűnagyságok nem változtathatók meg.

A mintában szereplő pontok közül nem mindegyik szükséges egy adott feladat esetén, az alább felsoroltakra pedig minimális terjedelmet írunk elő. A nem releváns pontok tartalma legyen a "Nincs információ" szöveg.

Az alábbi pontokat mindenképpen ki kell tölteni, ha megadott, egy minimális terjedelemben:

1. Bevezetés

2.2. (A probléma megfogalmazása) min. 2 oldal

2.3. (A termék helye) min 1-2 oldal

3.4 (Felhasználói környezet)

4.2 (A termék használatának előnyei)

4.3 (Feltételezések és függőségek)

5. (A végtermék jellemzői) min. 2 oldal

7. (Minőségi elvárások)

9. (Kockázat lista)

10.(Szótár) min. 1 oldal
---

2. Projekt terv
Egy ajánlott felépítés megtalálható a dokumentum minták között.

3. Munkanapló

(link)
https://users.iit.uni-miskolc.hu/~mileff/szt/H2.html

**Comment by kzsofia12** [comment]
[vizio.pdf](https://github.com/marcibaumel/SpeedCard/files/5322969/vizio.pdf)

**Comment by kzsofia12** [comment]
Ez az alap, még ehhez jön a szótár és megcsinálom HTML-ben

**Comment by kzsofia12** [comment]
Date: Mon, 5 Oct 2020 17:21:43 +0200
Subject: SWTECH=SpeedCards
From: "Zsófia Korita" <korita.zsofi12@gmail.com>
To: arvai.laszlo@iit.uni-miskolc.hu

Jó napot!
Ezen a linken elérhető a munkanapló illetve az aktuális dokumentumok: 
https://marcibaumel.github.io/SpeedCard/
A Vízió dokumentum így megfelelő lesz? A szótár részt egyenlőre még nem tartalmazza, de a mai vagy a holnapi nap folyamán már az is bele fog kerülni. Illetve milyen időpontban lenne jó az online konzultáció, hogy megbeszéljük, mit javítsunk a dokumentumon?

Válaszát előre is köszönöm.
