### ISSUE TITLE
9. (Kockázat lista)

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#23]

**Comment by Rokli02** [comment]
## 9. Kockázati lista
Az eddigi fejlesztés során nem botlottunk olyan problémá(k)ba, ami a fejlesztés határidejét növelné, viszont a közeljövőben több ilyen kockázat is fel fog merülni becsléseink szerint: 

1.  A játék grafikus megjelenítéséhez megalakult egy elképzelés a fejlesztőcsapat fejében, viszont nem tudjuk, hogy ez mennyire bonyolultan, nehezen megvalósítható, továbbá azt sem feltétlenül tudjuk, hogy ez mennyi időbe fog kerülni, hogy teljesen elkészüljön.
2. Az adatbázis, amit a játék használ több alkalommal is bővítve lesz, viszont ez vezethet ahhoz, hogy egy idő után olyan naggyá váljon, ami már nehezen kezelhető, esetleg rosszabb esetben a programozási nyelv amin íródott, ne tudja azt megfelelően használni.
3. Optimalizálás, ha szükséges. Ez a legtöbb játékgyártó cégnek egy igen csak nehéz feladat, amit általában nem tudnak a játék kiadása előtt megvalósítani, mi azonban ezt is meg akarjuk csinálni az előtt, hisz nem akarunk olyan szoftvert kiadni, amire mi sem lennénk büszkék. Erre akkor lenne szükség, ha teljesítménybeli problémák lennének, tehát a játék futása nem lenne folyamatos, időnként megakadna, talán folyamatosan akadozva menne.
Másik megközelítésből pedig a véletlen folytán létrejött bugok kijavítása, esetleg az olyan problémák, mint a Memory Leak megszüntetése.
4. A játék motorját nem mások által létrehozott motorra építenénk fel, hanem mi magunk csinálnánk meg, éppen ezért a megvalósítás több programozási problémába is ütközhet.
5. A játékhoz tartozó szerverek létrehozása, ami 3 féle képen lenne megoldható:
° *Bérelt szerverek*, ilyenkor a szerverekkel teljesítménybeli problémák lehetnek, ha nem megfelelően drága van alkalmazva, viszont az sok pénzbe kerül.
° *Általunk összeállított szerverek-szervergépek*, nekünk kell biztosítani olyan gépeket, amik képesek adott számú ember lekezelésére.
° *Szerver-kliens modell a felhasználók közt*, túlzottan függ a felhasználók internetminőségétől a szerverek teljesítménye.


### Kockázati tényezőket megszüntető/csökkentő intézkedések:
- **1. pont megoldása:** Grafikus felület minél egyszerűbbé, de annál stílusosabbá és használhatóbbá tétele.
- **2. pont megoldása:** Egy olyan határ meghúzása, amit átlépve már nem bővítjük az adatbázist, csak ha feltétlenül muszáj.
- **3. és 4. pont megoldása:** Átlagosnál nagyobb odafigyelés és több rászánt időt kell ezekre fordítani.

**Comment by Rokli02** [comment]
kb. 45 perc

**Comment by marcibaumel** [comment]
👍
