### ISSUE TITLE
2. Bevezetés FINAL

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#25]

**Comment by MrDxD-SoulAdmin** [comment]
Kártyajáték scfii, rts alapon nyugvó 5 line kb

**Comment by MrDxD-SoulAdmin** [comment]
A mi szoftwareünk egy kártyajáték amely a Hearthstone, Yu-Gi-Oh! és a Gwent című játékok játékmehanikáit az RTS alapjaira helyezve teremt egy új játékot. Ez a játék témáját tekinteve Sci-fi témájú játék  sok érdekes játékmehanikával. A játékmenet közbeni döntéssorozattal pedig a játékosok döntéshozatali és startégiai képességét tennénk próbára.

**Comment by marcibaumel** [comment]
👍

**Comment by kzsofia12** [comment]
Rövid...

**Comment by MrDxD-SoulAdmin** [comment]
A mi szoftverünk egy kártyajáték amely a Hearthstone, Yu-Gi-Oh! és a Gwent című játékok 
játékmechanikáit az RTS alapjaira helyezve teremt egy új játékot.
Ez a játék témáját tekintve Sci-fi témájú játék sok érdekes pályával, ami eleinte az űrben fog játszódni, 
de a további kiegészítők-ben újabb pályákkal és korokkal ismerkedhet meg a játékos.
Ezeket a pályákat színesítik tovább a változatos játékmechanikák.
A játék elsajátításához a játékosnak játék közben stratégikusan kell gondolkodnia hogyha megszeretné nyerni a mérkőzést, 
mivel a játékban sok lap és változatos képességek is jelen vannak.
A játékmenet közbeni döntéssorozattal pedig a játékosok döntéshozatali és stratégiai képességét 
tennénk próbára.
