### ISSUE TITLE
2.3. (A termék helye) min 1-2 oldal

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#27]

**Comment by husoczkidani** [comment]
2.3 Az elkészült termék helye

A termék alapötlete egy játék, ezért a már kész szoftvert a játékiparban tervezzük elhelyezni. 

Napjainban nagyon sok gyerek és felnőtt szereti elütni szabadidejét azzal, hogy videójátékokkal játszanak, ennek a játéknak is ez a célja, az emberek szórakoztatása szabadidejükben. 

A fő célközönség a 14 és 30 éves felhasználók, mivel statisztikák alapján ez a korosztályintervallum játszik a legtöbbet online, viszont ez nem azt jelenti, hogy az intervallumon kívüli korosztály nem játszhat a játékkal, bármilyen kortól lehet vele játszani. Mivel a kártyajáték alaptörténete egy Sci-Fi világban játszódik, ezért a Sci-Fi, a stratégiai játékok és a kártyajátékok kedvelőit is nagymértékben csábítani fogja. A játék elsősorban asztali számítógépre van tervezve, de a jövőben mobil alkalmazásként is szerepet fog játszani, így akár menet közben, kis időre is elővehetik és játszhatnak vele a felhasználók.

Több hasonló játék is létezik, már a játékiparban, ilyenek például azok a játékok, amiből a főbb ötleteket vettük, a HearthStone, a Yu-Gi-Oh és a Gwent. Ezek mind kártyajátékok, azonban ezek a játékok nem hasonlítanak egymásra, mint ahogy ez a játék sem fog hasonlítani a többire.
A történet, a játékmechanika és a játékmenete is egyedi, és különbözik a már meglévő alternatíváktól. Másféle megoldást alkalmaztunk a csaták lebonyolítására, a kártyák elhelyezkedésére, tulajdonságaikra, és a játékban lévő erőforrásokra.

**Comment by Rokli02** [comment]
Az elsőhöz gondolathoz talán platformmal lehet bővíteni hova kerül ki, hova nem.
A többihez nincs semmi új további gondolat, benne van minden, aminek lenni kell.
