### ISSUE TITLE
3.4 (Felhasználói környezet)

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#28]

**Comment by MrDxD-SoulAdmin** [comment]
Levi te gyökér nézd meg az oldalt

**Comment by MrDxD-SoulAdmin** [comment]
**Milyen platformon fog futni az átadott alkalmazás, és várhatóan változni fog-e?**

Az alkalmazás Java környezetben fog futni A Beta kizárólag pc platformon OS függetlenül lesz elérhető de a későbbiekben PS és xbox Consolen és Switchen is aztán kiterjesztjük mobilokra. Változni a felépítés nem fog hanem az Updatek és DLC-k kiadásával tervezzük új pályákat és lapokat belevinni a játékba ezzel is színesíteni a játékmenetet.

**Hány felhasználó fogja használni egy időben átlagosan, és hány felhasználó várható maximálisan?**

A játék Beta verziójában még nem lesz elérhető a multiplayer játékmód  de a kész verzióban ez is elérhető lesz.

felhasználói szemszögből 1 meccs fog elkezdődni ahol 1v1 meccsfelosztásban játszanak a játékosok egymás ellen és egy időben csak 1 active meccs lesz, tehát 1 meccsen 2 játékosnak kell részt vennie.

Szerver oldali szemszögből 1v1es meccsek fognak kezdődni viszont egyidejűleg akár több is. Ezáltal ebből a szemszögből a résztvevő játékosok száma minimum 2 maximum pedig annyi amennyit a szerver erőforrásai elbírnak.

**Van-e valami várható trendje a felhasználószámnak?**

A várható trend az az lenne hogy amikor egy frissítés vagy DLC érkezik a játékhoz akkor az érdekelni fogja a régebbi játékosokat és lehet hogy újabb játékosokat is vonzani fog és megtetszik nekik.

**Mennyi ideig fogja használni a rendszert egy felhasználó, és ez mennyire változó?**

Mennyi ideig fogja egy felhasználó használni a rendszert az változó, révén hogy valamennyire a stratégiára is épít a játék ha valaki esetleg nem annyira stratégikus akkor lehetnek hosszabb meccsek de ha valakinek jobb a stratégiája akkor azok gyorsabb meccsek lesznek. Egy meccs hossza attól is fog függeni hogy ki mennyire szokik hozzá a játékhoz(beletanul), mivel gyorsabbak lesznek a meccsek ha már a játékosok ismerik a lapokat és a meccsek menetét.

**Milyen különleges körülményekkel kell számolni (egyedi hardware eszközök, mobil kliensek stb.)?**

A játék futtatásához nem szükséges semmi különleges hardware vagy software elem ,sem kliens egyszerűen csak el kell indítani és már is mehet a játék.

**Milyen más alkalmazásokkal kell várhatóan integrálni a terméket?**

Mivel a játék nem igényel semmilyen különleges hardwaer/software egységet és kliens sem kell hozzá ezét csak magára a java-ra van szükség azon belül is a JVM-re (Java Virtual Machine). Erre ezért lesz szükség mivel a játékot ez fogja elindítani és futtatni.

**Comment by marcibaumel** [comment]
👍
