### ISSUE TITLE
4.2 (A termék használatának előnyei)

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#29]

**Comment by Rokli02** [comment]
## A termék használatának előnyei
| Használati előnyök amit a termék biztosít | 
| ----------------------------------- | 
| A szoftver használata több mint alkalmas, hogy az ember egyébként unalomban töltött idejét egy, vagy akár több szórakoztató mérkőzésbe fektesse |
| Ebben a játékban olyan taktikai gondolkodás alakulhat ki, ami akár más játékban is alkalmazható, nem csak ebben  |
| Az előbb említett gondolkodás mellett kialakulhat olyan szinten az előregondolás készsége, mint amilyen egy haladó szintű sakk játékosnak van |
| Hogyha barátaink ellen/velük játszunk, akkor egy tartalmas és mókás közös elfoglaltság lehet |
| Amennyiben úgy ülünk le játszani gép elé, hogy nincs sok időnk, ez a játék megfelelő választás hisz a leghosszabb kör is maximum 10 percig tart |
| Abban az esetben, ha nem szeretnénk pénzt költeni játékra, akkor is játszható ez a szoftver, hisz egy olyan ingyenes modellt használunk, ami ezt lehetővé teszi |

**Comment by Rokli02** [comment]
15 perc leírni de 30 percig gondolkoztam mi a rák előnye lehet :'D

**Comment by marcibaumel** [comment]
👍
