### ISSUE TITLE
7. (Minőségi elvárások)

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#30]

**Comment by husoczkidani** [comment]
7. Minőségi elvárások

A játék elsősorban asztali számítógépen, majd a jövőben telefonos applikációként lesz elérhető. Mivel ez egy kártyajáték ezért, sem nagyobb pályákat, sem nagyobb modelleket nem kell gyorsan belöltenie a rendszernek, mint például egy MMO RPG-nél, ezért a játék hardverigénye viszonylag kicsi.
A játszáshoz szükséges lesz az internetelérés, mivel a tervek között szerepel a "játékos vs játékos" mód is, viszont a válaszidő nem a legfontosabb változó egy kártyajátékban, azonban lesz egy bizonyos határ ahol a rendszer kilépteti a játékost, majd lehetőség lesz újracsatlakozásra.
A felhasználó adatainak ( felhasználónév, jelszó, email) biztonságos tárolása fő prioritás, a feltörések, adatlopások elkerülése érdekében.
Az alap játékfelület letisztul és egyszerű lesz a jó átláthatóság érdekében, így könyebb lesz a felhasználónak tájékozódni a menüben és a harcmezőn is.

**Comment by husoczkidani** [comment]
Körülbelül 20 perc, volt

**Comment by marcibaumel** [comment]
Teljesen jó, ha még akarnál hozzá írni a végtermék jellemzőiből átrakhatsz ide pár dolgot de szerintem így is korrekt 👍
