### ISSUE TITLE
4.3 (Feltételezések és függőségek)

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#34]

**Comment by Rokli02** [comment]
4.3 Feltételezések és függőségek:

Az általunk fejlesztett játékszoftverhez az előre minimális számítógépigény minden felhasználó számára könnyen teljesíthető.
A merevlemezen foglalt terület körülbelül 3 és fél gigabyte helyet fog foglalni, bár ez a későbbiekben növekedhet attól függően, hogy a végtermék mennyi textúrát fog tartalmazni és milyen részleteset.
A processzor igény nem nagy, legalább egy AMD Fx-6300 fog kelleni, amivel élvezhető minőségben lehet játszani.
Videókártya alacsonyabb teljesítményű is lehet, bármilyen integrált videókártya megfelelő, hiszen ez egy kártyajáték, amiben nem kell a másodperc töredékei alatt részletes 3D-s modelleket, sem animációkat leképeznie.
A memória követelmény 1 Gigabyte nagyságú lesz, bár ez megint csak változhat a végleges grafika minőségétől.

**Comment by marcibaumel** [comment]
Hali, teljesen jó lett. Annyi megjegyzésem lenne, hogy az OP rendszerre is ki lehetne térni és lehet, hogy a végén az átláthatóság érdekében egy minimum és egy ajánlót gépigényt fellehetne tüntetni mint mondjuk a "gépigény.hu" szokott lenni. 

# +1
A kommentet is lehet szerkeszteni a markdown-nal, itt van hozzá egy kis help, ezzel egyszerűbb lesz Zsófinak utána szerkeszteni: 
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by Rokli02** [comment]
kb. 45 percet vett igénybe

**Comment by Rokli02** [comment]
Bővítés:
A játékhoz folyamatos internetkapcsolat szükséges, aminek  legalább 250 Kb/s gyorsaságúnak kell lenni a megfelelő működéshez. Ez többszörösére növekedhet amennyiben az felhasználó hoz létre egy egyéni (Custom) szervert.
Ahhoz, hogy le tudjuk tölteni a szoftvert és játszani tudjunk vele, szükséges egy Steam felhasználófiók, mivel ezen a platformon fogjuk közzétenni.
