### ISSUE TITLE
2.1 Üzleti lehetőségek

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#39]

**Comment by husoczkidani** [comment]
A projektünkben rejlő üzleti lehetőségek széleskörűek, hiszen egy játékról van szó, és mivel napjainkban az emberek többsége a szabadidejét játékok játszásával tölti, így a célközönség is nagy.
Az igaz, hogy a játékot ingyenesen játszhatóan szeretnénk kiadni, viszont a későbbi frissítések során, amikor már elérhető a sztory módon kívül a többjátékos mód is tervezzük bevezetni a Boltot, és a mikrotranzakciókat.
A Boltban a játékosok pénzért tudnak majd paklikat, kártyákat venni, nyílván ezeket nem akarjuk eltúlozni ezért nem lehet majd olyan kártyákat és paklikat venni amiket amúgy nem lehetne megszerezni máshogy a játékban. Továbbá a felhasználók tudnak majd kinézeteket/díszítéseket venni a kártyáikra és a pályára is.

**Comment by husoczkidani** [comment]
kb 20p volt

**Comment by marcibaumel** [comment]
Még bele lehetne írni a szezon rendszert. Amikor befizet a játékos egy szezonra és amikor szintet lép jutalmat kaphatna érte. Ez olyan mint a Fortnite-ban van vagy a most megjelent Rocket League ingyenes verziójában van megvalósítva.

**Comment by husoczkidani** [comment]
2.1 Üzleti lehetőségek

A projektünkben rejlő üzleti lehetőségek széleskörűek, hiszen egy játékról van szó, és mivel napjainkban az emberek többsége a szabadidejét játékok játszásával tölti, így a célközönség is nagy.
Az igaz, hogy a játékot ingyenesen játszhatóan szeretnénk kiadni, viszont a későbbi frissítések során, amikor már elérhető a sztory módon kívül a többjátékos mód is tervezzük bevezetni a Boltot, és a mikrotranzakciókat.
A Boltban a játékosok pénzért tudnak majd paklikat, kártyákat venni, nyílván ezeket nem akarjuk eltúlozni ezért nem lehet majd olyan kártyákat és paklikat venni amiket amúgy nem lehetne megszerezni máshogy a játékban. Továbbá a felhasználók tudnak majd kinézeteket/díszítéseket venni a kártyáikra és a pályára is.
Tervezünk egy szezon rendszert is bevezetni, amiben a játékosok különféle jutalmakat kaphatnak szintek elérésével és küldetések teljesítésével. Ennek lenne egy ingyenes része és egy fizetős része, amit szezon belépő megvásárlásával tudnak majd elérni a játékosok. A jutalmak jobbrésze nyilván a fizetős részben lenne benne, de azokat sem akarjuk kihagyni a jóból akik nem akarják megvenni ezt a Szezon belépőt.
