### ISSUE TITLE
3.1. Az érintettek összefoglalása

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#40]

**Comment by Rokli02** [comment]
| Elnevezés | Leírás | Szerep |
| - | - | - |
| Grafikus | Bármilyen felhasználó által látható és értelmezhető felületet hoz létre. | Kinézetet biztosít a játékhoz, amit az adott részletességű modellekhez hozzá lehet rendelni, esetleg a kezelő felületekhez létrehozott grafikát csinálja. |
| Engine fejlesztő | A játék alap mechanikáját hozza létre. | Felelő a játék bizonyos funkcióinak a működéséért, továbbá az új játék mechanikák implementálásáért. |
| Adatbázis kezelő | Nagy mennyiségű adat kezelésével foglalkozik. | A játék összes adatbázisát kezeli, ha újítás van, akkor hozzárendeli a megfelelő adatokhoz az újat és ezek közötti kapcsolatot hoz létre.  |
| Kreatív felelős | A játék kinézeti, működési és kivitelezési ötleteivel támogatja a csapatot. | Ő intézi, hogy a játék minél több ember számára élvezhető kivitelezéssel készüljön el, a játékhoz illő történettel és stílussal, továbbá ötletgazda. |
| Optimalizáló fejlesztők | Engine fejlesztők munkáját tovább finomítják | Egy félkész/kész terméket jobb, gyorsabb algoritmusokkal javítanak, hogy azok még gyorsabban, még jobb eredményt adjanak. Ha hiba van a termékben az ő feladatuk annak a megoldása. |
| Pénzügyi felelős | A vállalat pénzügyeivel foglalkozik | Megtervezi és kiosztja, hogy melyik projektekre mekkora támogatás adható és kiszámítja, hogy adott pénzügyi modellekkel mekkora pénz folyhat be a cég számára , bizonyos feltételek betartásával. |
| Modellező | 3D és 2D-s modellek létrehozása | A játékban szereplő modelleket megtervezi, létrehozza és implementáláshoz felkészíti |

**Comment by Rokli02** [comment]
Oké, valszeg teljesen félre értelmeztem
