### ISSUE TITLE
3.2. A felhasználók összefoglalása

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#41]

**Comment by Rokli02** [comment]
| Elnevezés | Leírás | Illetékes |
| - | - | - |
| Tartalom létrehozó | A program alapvető tartalmát megalkotják, legyen az történeti, vagy grafikai. | Kreatív felelős, Grafikus, Modellező |
| Programozó | A játék elemi és összetettebb részeit megvalósítja magas szintű programozói nyelven | Engine fejlesztő, Optimalizáló fejlesztő |
|  |  |  |

**Comment by Rokli02** [comment]
30 perc
