### ISSUE TITLE
3.4. Illetékesek adatai

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#42]

**Comment by kzsofia12** [comment]
Árvai László 
- Gyakorlatvezető 
- Elérhetősége: arvai.laszlo@iit.uni-miskolc.hu

Dr. Mileff Péter 
- Szoftvertechnológia tárgy előadója   
- Elérhetősége: mileff@iit.uni-miskolc.hu  

Baumel Márton 
- Csapatvezető
- Elérhetősége: marcibaumel@gmail.com
