### ISSUE TITLE
4.5. Installáció

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#43]

**Comment by MrDxD-SoulAdmin** [comment]
<h2><a name="45"></a>4.5 Installáció</h2>
    <p class="h2">
        A játékot nem kell telepíteni, elegendő csak letölteni és már futtatható formában is van 
        a játék, készen áll a használatra. Mielőtt azonban letöltjük a játékot előtte ellenőrizzük le hogy a gépünkön
        van-e Java JRE(Java Runtime Enviroment) telepítve, mivel ugyan a játékot nem kell telepíteni, de a java-t kell, mivel a játék
        java futtató környezetben fog csak működni , amiért a JVM(Java Virtual Machine) fog felelni. A java-t a  
        https://www.oracle.com/java/technologies/javase-downloads.html oldalról lehet letölteni és telepíteni. 
        A telepítés lépéseiről ugyan ezen az oldalon találtok egy dokumentációt.

        A telefonokhoz az installáció úgy történik, hogy a Steam Store-ból lesz letölthető egy szinkronizáló APK ami internet kapcsolattal,
        valamint Steam-es bejelentkezés után automatikusan a gépünkről szinkronizálja át és telepíti a játékot telefonunkra.
    </p>
