### ISSUE TITLE
6. Korlátozások

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#44]

**Comment by MrDxD-SoulAdmin** [comment]
<h1><a name="6"></a>6. Korlátozások</h1>
    <p class="h1">
        <u>A játék használatához szükséges:</u><br>
        <ul>
            <li>Stabil Internet Kapcsolat</li>
            <li>Számítógép / Okostelefon</li>
            <li>Active Steam Accaunt</li>
            <li>Java JRE vagy Java JDK</li>
        </ul>
        Ezek a Dolgok szükségesek a játék futtatásához. Az alapjáték minden mai számítógépen elfut.
        <u>Alap játék rendszerigény:</u>
        <ul>
            <li><b>CPU: </b>AMD FX-6300 Hexa-core 3.5GHz./ Intel Core i5-4690k 3.5Ghz</li>
            <li><b>Memória: </b>1 GB 1333MHz Ram.</li>
            <li><b>GPU: </b>3D modell lekezelést támogató, 512 VRAM-mal rendelkező.</li>
            <li><b>Merevlemez: </b>Legalább 4 GB szabad hellyel rendelkező.</li>
            <li><b>Operációs rendszer: </b>Windows 7 vagy újabb.</li>
        </ul>
        A rendszer követelmények nőhetnek a további DLC-kel és azokban szereplő új modellek miatt, de ezen kívül nincs más 
        korlátozási tényező. 
    </p>
