### ISSUE TITLE
4.1 A termék kapcsolatai

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#46]

**Comment by husoczkidani** [comment]
4.1 A termék kapcsolatai

A termék funkcionális komponensei:

- Adatbázis létrehozása és lekérdezése
- A felhasználók fiókjainak nyilvántartása 
- A kártyák és tulajdonságaik nyilvántartása 
- A felhasználók adatainak védelme
- Felhasználók közötti üzenetküldés és barátfelvétel

A rendszer a további frissítések során bővülni fog, így több funkcionális komponens is kerülhet még bele ( pl.: bolt, vásárlás, többjátékos módnál az ellenfelek kiválasztása).

**Comment by husoczkidani** [comment]
kb 20 perc volt
