### ISSUE TITLE
3.5. Felhasználók adatai

### ISSUE THREAD

**Issue by marcibaumel** [marcibaumel/SpeedCard#47]

**Comment by kzsofia12** [comment]
A felhasználóknak készülni fog egy profil oldal, amit böngészőn keresztül el tudnak érni.
Megtekinthető lesz rajta, hogy pillanatnyilag milyen szintű a játékban, tudja módosítani a bejelentkezési adatait, illetve látható lesz rajta a tranzakciós lista is.
